# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  #name = "Home"
  #url = "#about"
  #weight = 10

[[main]]
  name = "P+动态"
  url = "posts/"
  weight = 20


[[main]]
  name = "申请"
  #url = "#featured" #if you want like a built-in function, use this
  url = "publication/" #if you want to a separate page, use this.
  weight = 40

[[main]]
  name = "我们的团队"
  url = "#people"
  weight = 10

[[main]]
  name = "联系我们"
  url = "#contact"
  weight = 60

[[main]]
  name = "活动策划"  # Title of the link.
  url = "activities/"  # Widget Page folder name. Using / as the back drop
  weight = 35  # Position of the link in the navigation bar.


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
